application: blog-1122
version: 1
runtime: go
api_version: go1

skip_files:
- src/node_modules/.*
- src/components/.*
- ^(.*/)?.*\.un~$
- src/*.md

handlers:
- url: /
  static_files: src/www/index.html
  upload: src/www/index.html
- url: /
  static_dir: src/www
- url: /go/*
  script: _go_app

